-----------------------PROCEDIMIENTOS ALMACENADOS DE USUARIOS---------------------

/* Creaciòn Usuario (CREATE) */

CREATE OR REPLACE PACKAGE CREACION_CUENTA
IS
    PROCEDURE CREAR_USUARIO(nom VARCHAR2, apell VARCHAR2, usua VARCHAR2,
    cont VARCHAR2, rol VARCHAR2);
    PROCEDURE VERIFICAR_REPETIDO(usua VARCHAR2);
END;
/
CREATE OR REPLACE PACKAGE BODY CREACION_CUENTA
IS
    PROCEDURE CREAR_USUARIO(nom VARCHAR2, apell VARCHAR2, usua VARCHAR2,
    cont VARCHAR2, rol VARCHAR2)
     IS
       BEGIN
        INSERT INTO USUARIOS (nombre, apellido, Nom_usuario, contrasena, rol)
        VALUES (nom, apell, usua, cont, rol);
       END;
       
       PROCEDURE VERIFICAR_REPETIDO(usua VARCHAR2)
        IS
         usuario USUARIOS.NOM_USUARIO%TYPE;
         BEGIN
          SELECT NOM_USUARIO INTO usuario FROM USUARIOS
          WHERE NOM_USUARIO = usua;
         END;
END;

/* Inicio de sesion*/

CREATE OR REPLACE PACKAGE INICIO_SESION
IS
    PROCEDURE VERIFICAR_USUARIO(usua VARCHAR2, cont VARCHAR2);
    PROCEDURE VERIFICAR_ROL(usua VARCHAR2, rol_cursor OUT SYS_REFCURSOR);
END;
/
CREATE OR REPLACE PACKAGE BODY INICIO_SESION
IS 
    PROCEDURE VERIFICAR_USUARIO(usua VARCHAR2, cont VARCHAR2)
     IS
       V_USUARIO USUARIOS.NOM_USUARIO%TYPE;
       V_CONTRASENA USUARIOS.CONTRASENA%TYPE;
       BEGIN
        SELECT CONTRASENA INTO V_CONTRASENA FROM USUARIOS
        WHERE NOM_USUARIO = usua AND CONTRASENA = cont;
       END;
       
       PROCEDURE VERIFICAR_ROL(usua VARCHAR2, rol_cursor OUT SYS_REFCURSOR)
       IS
       BEGIN
        OPEN rol_cursor FOR SELECT ROL FROM USUARIOS WHERE NOM_USUARIO = usua;
       END;
END;

select * from usuarios;

CREATE OR REPLACE PACKAGE PERFIL
IS
 PROCEDURE MOSTRAR_DATOS_USUARIO(usua_act VARCHAR2, datos_usuario OUT SYS_REFCURSOR);
 PROCEDURE ACTUALIZAR_USUARIO(usua_act VARCHAR2,  nom VARCHAR2, apell VARCHAR2, usua VARCHAR2, 
 cont VARCHAR2,rol VARCHAR2);
 PROCEDURE ELIMINAR_USUARIO(usua_act VARCHAR2);
END;
/
CREATE OR REPLACE PACKAGE BODY PERFIL
IS 
 PROCEDURE MOSTRAR_DATOS_USUARIO(usua_act VARCHAR2, datos_usuario OUT SYS_REFCURSOR)
 IS
  BEGIN
   OPEN datos_usuario FOR SELECT * FROM USUARIOS WHERE NOM_USUARIO = usua_act;
  END;
    
    PROCEDURE ACTUALIZAR_USUARIO(usua_act VARCHAR2, nom VARCHAR2, apell VARCHAR2, usua VARCHAR2, cont VARCHAR2,
    rol VARCHAR2)
    IS
     BEGIN
      UPDATE Usuarios SET NOMBRE = nom,
      APELLIDO = apell,
      NOM_USUARIO = usua,
      CONTRASENA = cont,
      ROL = rol
      WHERE NOM_USUARIO = usua_act;
     END;
     
     PROCEDURE ELIMINAR_USUARIO(usua_act VARCHAR2)
     IS
      BEGIN
       DELETE FROM Usuarios WHERE NOM_USUARIO = usua_act;
      END;
  
END;

execute PERFIL.ACTUALIZAR_USUARIO('prueba', 'jose pablo', 'duran', 'prueba', '123', 'Cliente');

-----------------------PROCEDIMIENTO ALMACENADO DE BICICLETAS CONSULTA---------------------

CREATE OR REPLACE PROCEDURE seleccionarBicicletas(bicis out sys_refcursor)
AS

 BEGIN
  OPEN bicis FOR SELECT ID_BICICLETA, NOMBRE, PRECIO, NOMBRE_FRENOS, NOMBRE_TRANSMISION, NOMBRE_SUSP, NOMBRE_RUEDAS, NOMBRE_MARCO, Nombre_MARCA
 FROM BICICLETAS INNER JOIN FRENOS ON
  bicicletas.ID_FRENOS = frenos.ID_FRENOS
   INNER JOIN TRANSMISION ON
    bicicletas.ID_TRANSMISION = transmision.ID_TRANSMISION
     INNER JOIN SUSPENSION ON
      bicicletas.ID_SUSPENSION = SUSPENSION.ID_SUSPENSION
       INNER JOIN RUEDAS ON
        bicicletas.ID_RUEDAS = RUEDAS.ID_RUEDAS
         INNER JOIN MARCO ON 
          bicicletas.ID_MARCO = MARCO.ID_MARCO
           INNER JOIN MARCA ON
            bicicletas.ID_MARCA = MARCA.ID_MARCA
  Order by ID_BICICLETA ASC;
END;


------------------------------------------------------------------------------------------------------------------
--PROCEDIMIENTO ALMACENADO PARA AGREGAR BICIS
create or replace PROCEDURE AGREGAR_BICI(
          ADD_ID_BICICLETA IN BICICLETAS.ID_BICICLETA%TYPE,
          ADD_NOMBRE IN BICICLETAS.NOMBRE%TYPE,
          ADD_PRECIO IN BICICLETAS.PRECIO%TYPE,
          ADD_ID_FRENOS IN BICICLETAS.ID_FRENOS%TYPE,
          ADD_ID_TRANSMISION IN BICICLETAS.ID_TRANSMISION%TYPE,
          ADD_ID_SUSPENSION IN BICICLETAS.ID_SUSPENSION%TYPE,
          ADD_ID_RUEDAS IN BICICLETAS.ID_RUEDAS%TYPE,
          ADD_ID_MARCO IN BICICLETAS.ID_MARCO%TYPE,
          ADD_ID_MARCA IN BICICLETAS.ID_MARCA%TYPE)
AS
BEGIN
 INSERT INTO BICICLETAS (ID_BICICLETA, NOMBRE, PRECIO, ID_FRENOS, ID_TRANSMISION,ID_SUSPENSION,ID_RUEDAS,ID_MARCO,ID_MARCA) 
 VALUES (ADD_ID_BICICLETA,ADD_NOMBRE,ADD_PRECIO,ADD_ID_FRENOS,ADD_ID_TRANSMISION,ADD_ID_SUSPENSION,ADD_ID_RUEDAS,ADD_ID_MARCO,ADD_ID_MARCA);
END;

/* ESTO ES NUEVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO*/
--PROCEDIMIENTO ALMACENADO PARA AGREGAR DATOS A LA FACTURA
create or replace PROCEDURE DETALLE_FACTURA(
          ADD_DESCRIPCION IN DetalleFactura.DESCRIPCION%TYPE,
          ADD_CANTIDAD IN DetalleFactura.CANTIDAD%TYPE,
          ADD_PRECIO IN DetalleFactura.PRECIO%TYPE,
          ADD_MONTO IN DetalleFactura.MONTO%TYPE)
AS
BEGIN
 INSERT INTO DetalleFactura (DESCRIPCION, CANTIDAD, PRECIO, MONTO) 
 VALUES (ADD_DESCRIPCION,ADD_CANTIDAD,ADD_PRECIO,ADD_MONTO);
END;

-----------------------PROCEDIMIENTO ALMACENADO DE Factura Detalle CONSULTA---------------------

CREATE OR REPLACE PROCEDURE seleccionarDetalle(detalle out sys_refcursor)
AS
 BEGIN
  OPEN detalle FOR SELECT *
 FROM DetalleFactura;
END;

----------------------------------------------------------------------------------------------------
--PROCEDIMIENTO ALMACENADO PARA ELIMINAR BICIS
create or replace PROCEDURE ELIMINAR_BICI(DEL_BICICLETA IN BICICLETAS.ID_BICICLETA%TYPE)
AS
BEGIN
 DELETE FROM BICICLETAS 
 WHERE ID_BICICLETA=DEL_BICICLETA;
END;

-----------------------------------------------------------------------------------------------------
--PROCEDIMIENTO ALMACENADO PARA ACTUALIZAR BICICLETAS
create or replace PROCEDURE ACTUALIZAR_BICI(
          UPD_ID_BICICLETA IN BICICLETAS.ID_BICICLETA%TYPE,
          UPD_NOMBRE IN BICICLETAS.NOMBRE%TYPE,
          UPD_PRECIO IN BICICLETAS.PRECIO%TYPE,
          UPD_ID_FRENOS IN BICICLETAS.ID_FRENOS%TYPE,
          UPD_ID_TRANSMISION IN BICICLETAS.ID_TRANSMISION%TYPE,
          UPD_ID_SUSPENSION IN BICICLETAS.ID_SUSPENSION%TYPE,
          UPD_ID_RUEDAS IN BICICLETAS.ID_RUEDAS%TYPE,
          UPD_ID_MARCO IN BICICLETAS.ID_MARCO%TYPE,
          UPD_ID_MARCA IN BICICLETAS.ID_MARCA%TYPE)
AS
BEGIN
  UPDATE BICICLETAS
  SET ID_BICICLETA = UPD_ID_BICICLETA,
   NOMBRE = UPD_NOMBRE,
   PRECIO = UPD_PRECIO,
   ID_FRENOS = UPD_ID_FRENOS,
   ID_TRANSMISION = UPD_ID_TRANSMISION,
   ID_SUSPENSION = UPD_ID_SUSPENSION,
   ID_RUEDAS = UPD_ID_RUEDAS,
   ID_MARCO = UPD_ID_MARCO,
   ID_MARCA = UPD_ID_MARCA
  WHERE 
    ID_BICICLETA = UPD_ID_BICICLETA;

END;